### ISSUE TITLE
Triangle before a collection

### ISSUE THREAD

**Issue by Jako** [modxcms/Collections#119]
A filled collection gets a folder icon (which is ok – bars would be somehow better) and a triangle to open that folder but only if the resource tree is reloaded. Seems to be solved half way in #13 (only until the resource tree is reloaded).

Revo 2.3.1 and Collections 3.0.2.

**Comment by TheBoxer** [comment]
I don't experience probleme having folder icon in filled collections, having there bars...

And currently there is no solution for the triangle problem to keep it compatible with 2.2

**Comment by Jako** [comment]
Example image (Folders 17, 18, 19 and 21 are CollectionContainer, CollectionContainer 17, 18 and 19 containing modDocument children, CollectionContainer 21 is empty):
![tree](https://cloud.githubusercontent.com/assets/148371/5647693/9e923134-9688-11e4-8a5f-4bab58f84f76.png)

It is a CSS specifity problem (.x-tree-node-collapsed .tree-folder:before succedes .collectioncontainer:before):
![tree-devtools](https://cloud.githubusercontent.com/assets/148371/5647753/2be9c7e0-9689-11e4-834e-0876b6cf0c52.png)

Could be solved by
```
.collectioncontainer:before {
content: "\f0c9" !important;
}
```

**Comment by TheBoxer** [comment]
Oh, you are on Revo 2.3.1. Update to 2.3.2 and it will be fine.
