### ISSUE TITLE
Site Broken after updating to Collections 3.1.0-pl

### ISSUE THREAD

**Issue by matdave** [modxcms/Collections#121]
After updating to Collections 3.1.0-pl on MODX 2.3.2 my site failed to work.  The screen was taken over by the menu nav, and had an error at the top stating: 

[OnManagerPageInit]

Notice:  Undefined index: debugUser in /home/hmcw/core/components/quip/model/quip/quip.class.php on line 132

Uninstalling and reverting to 3.0.2 resolved the issue.

**Comment by matdave** [comment]
I ran the update on a site in a different server and it worked... not sure what's going on here.  The working site didn't throw any errors during update.  Quip is installed on both sites. 

<pre>
Console running...
Attempting to install package with signature: collections-3.1.0-pl
Package found...now preparing to install.
Grabbing package workspace...
Workspace environment initiated, now installing package...
Skipping vehicle object of class modPluginEvent (data object exists and cannot be upgraded); criteria: Array ( [pluginid] => 23 [event] => OnManagerPageInit ) 
Skipping vehicle object of class modPluginEvent (data object exists and cannot be upgraded); criteria: Array ( [pluginid] => 23 [event] => OnBeforeDocFormSave ) 
Skipping vehicle object of class modPluginEvent (data object exists and cannot be upgraded); criteria: Array ( [pluginid] => 23 [event] => OnResourceBeforeSort ) 
Skipping vehicle object of class modPluginEvent (data object exists and cannot be upgraded); criteria: Array ( [pluginid] => 23 [event] => OnDocFormPrerender ) 
Skipping vehicle object of class modPluginEvent (data object exists and cannot be upgraded); criteria: Array ( [pluginid] => 23 [event] => OnBeforeEmptyTrash ) 
Attempting to preserve files at /xxx/xxx/public_html/assets/components/collections into archive /xxx/xxx/core/packages/collections-3.1.0-pl/modCategory/de66486f0e3b117efa3786789c0bd6c1.1.preserved.zip
Attempting to preserve files at /xxx/xxx/core/components/collections into archive /xxx/xxx/core/packages/collections-3.1.0-pl/modCategory/de66486f0e3b117efa3786789c0bd6c1.2.preserved.zip
Error adding field CollectionTemplate->back_to_collection_label: Array ( [0] => 42S21 [1] => 1060 [2] => Duplicate column name 'back_to_collection_label' ) 
Error adding field CollectionTemplate->back_to_selection_label: Array ( [0] => 42S21 [1] => 1060 [2] => Duplicate column name 'back_to_selection_label' )
Error adding field CollectionTemplate->selection_create_sort: Array ( [0] => 42S21 [1] => 1060 [2] => Duplicate column name 'selection_create_sort' ) 
Error adding field CollectionTemplate->child_hide_from_menu: Array ( [0] => 42S21 [1] => 1060 [2] => Duplicate column name 'child_hide_from_menu' ) 
Error adding field CollectionTemplate->child_published: Array ( [0] => 42S21 [1] => 1060 [2] => Duplicate column name 'child_published' ) 
Error adding field CollectionTemplate->child_cacheable: Array ( [0] => 42S21 [1] => 1060 [2] => Duplicate column name 'child_cacheable' ) 
Error adding field CollectionTemplate->child_searchable: Array ( [0] => 42S21 [1] => 1060 [2] => Duplicate column name 'child_searchable' ) 
Error adding field CollectionTemplate->child_richtext: Array ( [0] => 42S21 [1] => 1060 [2] => Duplicate column name 'child_richtext' ) 
Error adding field CollectionTemplate->child_content_type: Array ( [0] => 42S21 [1] => 1060 [2] => Duplicate column name 'child_content_type' ) 
UPDATE `modx_site_content` WHERE `modx_site_content`.`class_key` = :0 Array ( [/:0\b/] => 'SelectionContainer' ) 
UPDATE `modx_site_content` WHERE `modx_site_content`.`class_key` = :0 Array ( [/:0\b/] => 'SelectionContainer' ) 
Error updating modResource instances using query UPDATE `modx_site_content` WHERE `modx_site_content`.`class_key` = 'SelectionContainer' 
Skipping vehicle object of class modSystemSetting (data object exists and cannot be upgraded); criteria: Array ( [key] => collections.mgr_date_format )
Skipping vehicle object of class modSystemSetting (data object exists and cannot be upgraded); criteria: Array ( [key] => collections.mgr_time_format )
Skipping vehicle object of class modSystemSetting (data object exists and cannot be upgraded); criteria: Array ( [key] => collections.mgr_datetime_format ) 
Skipping vehicle object of class modSystemSetting (data object exists and cannot be upgraded); criteria: Array ( [key] => collections.user_js ) 
Skipping vehicle object of class modSystemSetting (data object exists and cannot be upgraded); criteria: Array ( [key] => collections.user_css ) 
Skipping vehicle object of class modSystemSetting (data object exists and cannot be upgraded); criteria: Array ( [key] => mgr_tree_icon_collectioncontainer ) 
Skipping vehicle object of class modSystemSetting (data object exists and cannot be upgraded); criteria: Array ( [key] => mgr_tree_icon_selectioncontainer ) 
Skipping vehicle object of class modSystemSetting (data object exists and cannot be upgraded); criteria: Array ( [key] => renderer_image_path ) 
Successfully installed package collections-3.1.0-pl
</pre>

**Comment by TheBoxer** [comment]
From which version did you update?

**Comment by matdave** [comment]
I updated from 3.0.2, this was from a "re" install.  I had to uninstall it to get my site working, then i tried to reinstall it.

**Comment by TheBoxer** [comment]
ah ok, than those errors are fine. Did you get any errors on the first shot?

**Comment by matdave** [comment]
I did the update and then left. I'm not sure where I would find those errors after the fact.

**Comment by TheBoxer** [comment]
I suppose nowhere :) Is it working after reinstall or same error still?

**Comment by matdave** [comment]
It is causing the same issue after the reinstall, so I reverted it back to 3.0.2

**Comment by TheBoxer** [comment]
Can you check `debug` system setting on both sites?

**Comment by matdave** [comment]
I toggled between 1 and 0 on the broken site when I was just trying to figure out what was going on.  It didn't really make a difference.

**Comment by TheBoxer** [comment]
That's weird, cause the section that's causing this problem in quip is triggered only with debug set to 1...

**Comment by matdave** [comment]
There we go. I completely removed a value from the debug setting, and it seems to be working.

**Comment by TheBoxer** [comment]
ok, I'll fix the quip so it's not throwing this error :)
