### ISSUE TITLE
[3.1.0] TV Image renderer not displaying images in the grid

### ISSUE THREAD

**Issue by beau-gosse** [modxcms/Collections#122]
After upgrading to **Collections 3.1.0** (from 3.0.2), images are no longer displayed in the grid. Here's a screenshot of the problem. 
![editing collections blog](https://cloud.githubusercontent.com/assets/509451/5783177/bffd090e-9d8e-11e4-8407-e2422c77cd0d.png)
**My image column has the following settings:**

Name | Renderer
------------ | -------------
tv_Image | Collections.renderer.image

I'm running MODX 2.3.2. The Image TV is set to use the filesystem as the media source. So nothing changed here. `[[++base_url]]` returns "/". My images are stored in `assets/img/blog` and they're loading just fine in the front end.  Am I missing something?

**Comment by sepiariver** [comment]
@beau-gosse if you inspect those missing image elements what are the paths you see please?

**Comment by beau-gosse** [comment]
@sepiariver it's funny, the paths look like this: `undefinedassets/img/blog/myimage.jpg`. I guess it's the undefinedassets that's causing this.

**Comment by TheBoxer** [comment]
@beau-gosse there was a small change in the image renderer in 3.1.0 version and I just found out that there's bug with it :)

To fix the renderer, open system settings and select collections namespace, you should see there setting with key `renderer_image_path`, please remove this setting and create new one with key `collections.renderer_image_path` and leave empty value. After clearing cache, it should start working...

**Comment by beau-gosse** [comment]
@TheBoxer it worked! Just so you know, there was no `renderer_image_path` setting for Collections in the system settings. So I didn't have to delete anything. I just created `collections.renderer_image_path` as instructed and it's working. 

Thanks for the fix. Feel free to close this issue whenever you like.

**Comment by TheBoxer** [comment]
Can you try to search for `renderer_image_path` it might be elsewhere, if you find it, you can delete it :)

**Comment by beau-gosse** [comment]
@TheBoxer I just saw it. It had no namepace attached to it. I deleted it.

**Comment by TheBoxer** [comment]
@beau-gosse 3.1.1 released, fixing this problem and some more ;)

**Comment by sylbal** [comment]
Hi,

I have a similar problem. Using modx-2.3.3 and Collections 3.1.1. The image is broken in the list, the image url looks like: http://www.mydomain.com/manager/undefinedassets/media/images/products/micro_300.jpg

The collections.renderer_image_path properties is set with {assets_url}media/images/products

Did I missed sth ? At this point, pretty_url are not activated, not sure it has an effect

**Comment by TheBoxer** [comment]
Replace the `{assets_url}` with the actual url

**Comment by sylbal** [comment]
Thank's for quick answer. This must be cached somewhere as I still have the "old" url after trying the full url and even after reseting the value to blank. Have cleared the cache via the "admin" menu but will continue to check if there is another cache to clear.

**Comment by TheBoxer** [comment]
Clearing cache via admin should be enough, you can try removing content of `/core/cache` folder...

**Comment by sylbal** [comment]
Finally fixed it :)
I had to set "compress_js" option in the manager section to off that it can refresh the compiled js with the wrong collections.renderer_image_path properties.
Then I had to update a bit the JS that is provided as example on the modx blog, the config object was ot correctly returned, due to the point in the property key, I guess.
```javascript
var imageRenderer = function(value, metaData, record, rowIndex, colIndex, store) {

    if (value != '' && value != null) {
        var baseUrl = MODx.config['collections.renderer_image_path'];
        if (value.indexOf('http') === 0) {
            baseUrl = '';
        }
        return '<div class="imagerenderer"><img src="' + baseUrl + value + '" width="100"></div>';
    }
};
```
