### ISSUE TITLE
Default children's template "(empty)"

### ISSUE THREAD

**Issue by Mikaro** [modxcms/Collections#123]
for Static Resources that points to PDF files

**Comment by TheBoxer** [comment]
Sorry, I have no idea what you mean. Can you provide more info & steps how to reproduce?

**Comment by Mikaro** [comment]
Hi TheBoxer.
sorry, my English is very bad, I try....
![default-template](https://cloud.githubusercontent.com/assets/1716779/5818509/6231e238-a0b6-11e4-8d2e-0ed1fe85e0d2.jpg)

in Collection's settings I must be able to set Default children's template "(empty)" 

Why? --> http://rtfm.modx.com/revolution/2.x/making-sites-with-modx/structuring-your-site/resources/static-resource
To Ensure your file is Transmitted Correctly, You Should use the (empty) template!

**Comment by TheBoxer** [comment]
Oh, ok, now I got it. I'll fix this ;)

**Comment by Mikaro** [comment]
temporary fix by a OnDocFormRender Plugin

thanks for the great work
I can not live without Collections :)
