### ISSUE TITLE
Empty view collections resources.

### ISSUE THREAD

**Issue by Owningonyou** [modxcms/Collections#126]
G.A.!
After moving modx site to web-server from local, i have been once problem. 
When I try to open collection,  i view empty content page .
I cleared all caches (including browser cache), de- and re-installed it and tried to remove it manually (including MySQL Database tables) before re-installation. Always the same result.
Please help! Sry, for my Eng. :(
Screen:
http://pixs.ru/showimage/1jpg_9513639_15810375.jpg

**Comment by TheBoxer** [comment]
Check if you have assets/components/collections in place and core/components/collections also in place. And if you can post screenshot of your chrome console, where might be some errors?

**Comment by Owningonyou** [comment]
All files on place.
On Console just one error, where i used Collection render.
http://pixs.ru/showimage/2jpg_2667712_15811517.jpg

**Comment by TheBoxer** [comment]
remove this renderer from collections view and try if it works

**Comment by Owningonyou** [comment]
Oh, thank you! It's just wrong path to JS file!)
