### ISSUE TITLE
Use rte as editor in column

### ISSUE THREAD

**Issue by pepebe** [modxcms/Collections#128]
I wonder ifi its possible to use the installed rte as the editor for a column. I've tried several things, but the only thing I've managed to do sofar is to confirm that 'htmleditor' works.

![bildschirmfoto 2015-02-09 um 15 29 38](https://cloud.githubusercontent.com/assets/667315/6108086/817bbae6-b070-11e4-9791-39c85c91802f.png)

This is already extremly useful, but I would rather see the RTE installed in MODX (ckeditor, tinymce, redactor, etc).

Did I miss something?

**Comment by TheBoxer** [comment]
If you manage to get it working elsewhere, I bet it will work also for Collections.

Anyway, I don't think that having RTE as a grid row editor is usefull. Inline editing is not the place where you should edit your content with RTE.

**Comment by pepebe** [comment]
One question left: I guess I might be missing the bigger picture here, but Is there a technical reason why you believe that editing content inside the grid is a bad thing?

Thanks.

**Comment by TheBoxer** [comment]
I don't believe that editing content from grid is bad thing. I believe that having RTE as inline editor is bad thing.
