### ISSUE TITLE
Not all children become a part of a collection

### ISSUE THREAD

**Issue by whitebyte** [modxcms/Collections#129]
Hi.
I have a parent resource with lots of childs (350+). After changing parent resource type from "Document" to "Collection" i've noticed that not all child resources became a part of a collection (see screenshot) 
![collection](https://cloud.githubusercontent.com/assets/7704186/6130205/78901e40-b165-11e4-820c-bf4f435e4c55.png)

All child resources have similar template and type. Does Collections have some kind of limits on max amount of childs? Maybe i miss something?
I have this issue on several different sites.
Revo 2.3.2-pl, 2.3.3-pl,  Collections 3.1.1-pl, 3.0.2-pl

**Comment by TheBoxer** [comment]
No, there is no limitation on template for collection childs, only limitation is that the child resource does not have any other children.

**Comment by whitebyte** [comment]
Definitely they doesn't, so i think it's a bug.

**Comment by TheBoxer** [comment]
It might be possible that the request for switching to Collections timeouted and all resources was not processed via Collection's plugin. Can you try opening any Resource that is not under Collections but should be and save it again, if it will appear in Collections?

**Comment by whitebyte** [comment]
It did the trick. Thank you!
