### ISSUE TITLE
Set hide_children_in_tree for Collections that do not have containers as a child

### ISSUE THREAD

**Issue by TheBoxer** [modxcms/Collections#13]
This will prevent displaying arrow before the Collection node in Resource tree when it has only Resource children (that are all hidden under children's tab).

**Comment by labr1005** [comment]
This works for me in MODX 2.3.2 to hide those triangles via css:

```
[ext\:tree-node-id="web_269"] i.x-tree-ec-icon.x-tree-elbow-plus {
    visibility: hidden;
}
```

where tree-node-id is "context" + "_" + "resource id".

**Comment by TheBoxer** [comment]
If you'll have nested collections, or folder under collections, it will not work properly

**Comment by labr1005** [comment]
That's true. This is just a dirty fix for the case as described by exside. I currently have this situation, too, where there's nothing nested but the editors **always** click on the triangle.

**Comment by christianseel** [comment]
1) Shouldn't `modResource`s have the `show_in_tree` flag set to `0`?

2) Shouldn't MODX recognize if all children have the `show_in_tree` flag set to 0 and don't show the little arrow?

**Comment by TheBoxer** [comment]
ad 1) resources under Collections have that flag set to 0
ad 2) yes it should :)

**Comment by christianseel** [comment]
Oops, (1) was a bug in Gitify (which is now fixed) :)
