### ISSUE TITLE
Add view. Empty dashboard if assigned

### ISSUE THREAD

**Issue by knightknight** [modxcms/Collections#132]
MODX Revolution 2.3.3-pl (advanced)
Collections 3.1.1-pl

Apache/2.2.26
PHP v5.4.37
MySQL v5.6.22

Views > Add view, set options: 

General Settings:   
 
    Default for templates: some-templatename

Collections Settings:

    Resource type selection: No
    Default children's template: empty

Create a new collection and under Setting > Collections > assign new collection view created.

Create child page in new collection and save. Back to Collection. Dashboard is empty. If I change the Setting > Collections > Blog (default installed) the dashboard will show the created resources. I did notice that the 'default children's template' for the child page did set when you created a new child.

The only work around I found is to duplicate the original 'Blog' collection view and work from that.

**Comment by TheBoxer** [comment]
Did you create any columns in the view? If not, there is only ID column by default and it's set as hidden -> you don't see any table in Children tab.

**Comment by knightknight** [comment]
doh! Now I see it. Working as it should. Thanks TheBoxer
