### ISSUE TITLE
No child resources

### ISSUE THREAD

**Issue by hitodev** [modxcms/Collections#136]
Usually with my own-managed servers and MODX websites Collections works fine.

But I have currently to deal with a shared hosting website and I have the following problem : when I create a child resource, nothing appear in the Collections list and the ajax "loading" stick in progress mode...

When I switch from resource type "Collections" to "native" MODX resource, I can see the previously created resources...

Any idea?

**Comment by TheBoxer** [comment]
Check console there should be an error in request

**Comment by hitodev** [comment]
There is an  Internal Server Error in console
http://xxxxxxxxx.com/dev/assets/components/collections/connector.php Internal Server Error 		64ms

**Comment by TheBoxer** [comment]
than you can't access that URL from browser, try to load that page, if it gives you server error you have something wrong with your server, probably file permissions.

**Comment by hitodev** [comment]
connectors.php url shows:
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

**Comment by sepiariver** [comment]
That's definitely a problem with the server. The connector URL should be available to you in your browser. You should get a JSON response, IIRC

**Comment by hitodev** [comment]
ok switched MODX folders from 705 to 755 and reinstalled Collections. Thanks!
