### ISSUE TITLE
[Enhancement] Only show resources with specific template in collection grid

### ISSUE THREAD

**Issue by hugopeek** [modxcms/Collections#138]
In other words: exclude resources that have a different template. Sometimes it is desirable to have a few resources of a different kind on the same level..

**Comment by theboxer** [comment]
What would happen with resources with different template?

**Comment by hugopeek** [comment]
They would show as regular children in the resource tree. Same as when you add a container resource to a Collection grid now..

**Comment by boformer** [comment]
This would be a great addition.

**Comment by boformer** [comment]
@theboxer Can you point me to the code that handles which resources are displayed in the grid, and which are displayed in the resource tree?

**Comment by theboxer** [comment]
https://github.com/modxcms/Collections/blob/master/core/components/collections/processors/mgr/resource/getlist.class.php
https://github.com/modxcms/Collections/blob/master/core/components/collections/model/collections/events/collectionsonbeforedocformsave.class.php
https://github.com/modxcms/Collections/blob/master/core/components/collections/model/collections/events/collectionsonbeforeemptytrash.class.php
https://github.com/modxcms/Collections/blob/master/core/components/collections/model/collections/events/collectionsonresourcebeforesort.class.php
