### ISSUE TITLE
Icons+Tags in Buttons / action JS not working

### ISSUE THREAD

**Issue by inreti** [modxcms/Collections#141]
I tried to change the buttons and replace the buttons text with a font-awesome icon. Creating a custom renderer is quite easy from the docs:
```
/* FontAwesome classes for iconified buttons */
var iconClass = {
    "edit": "icon-edit",
    "delete": "icon-trash-o",
    "duplicate": "icon-files-o",
    "publish": "icon-thumbs-o-up",
    "unpublish": "icon-thumbs-down",
    "view": "icon-eye"
};
var buttonsOnly = new Ext.XTemplate('<tpl for="."><div class="collections-title-column">'
    +'<tpl if="actions">'
    +'<ul class="actions" style="position:relative;">'
    +'<tpl for="actions"> '
    +'<li><a href="javascript:void(0);" class="controlBtn {className}" title="{text}">'
    +'<i class="icon icon-fw icon-2x {[ iconClass[values.key] ]}"></i>{[ iconClass[values.key] ? "":values.text ]}'
    +'</a></li>'
    +'</tpl>'
    +'</ul>'
    +'</tpl>'
    +'</div></tpl>',{
    compiled: true
});
Collections.renderer.buttonsOnly = function(value, metaData, record, rowIndex, colIndex, store) {
    return buttonsOnly.apply(record.data);
};
```
![screenshot from 2015-06-15 15 45 04](https://cloud.githubusercontent.com/assets/2852461/8161193/9163cd28-1375-11e5-8d45-c3cf23c0965f.png)

But now you can only click on the buttons, when you target the small padding of the buttons - if you hit the icon (which is indeed part of the button), no action is triggered. 
This seems to occur for every tag inside the controlBtn-link: if you just change the original _pagetitleWithButtons_ renderer with this line (just a span around button text):
```
+'<li><a href="javascript:void(0);" class="controlBtn {className}"><span>{text}</span></a></li>'
```
the problem is the same: clicking the text does nothing, clicking the padding of the button triggers action (tested with Chrome & FF). The JS console shows no error.

**Comment by TheBoxer** [comment]
Try to set `controlBtn {className}` classes also for the `i` element.

**Comment by inreti** [comment]
I tried that already - did not work. Will check it again.

**Comment by TheBoxer** [comment]
The listener is on entire row and it's checking for the controlBtn class of the target.... I may review how to do it differently :/

**Comment by inreti** [comment]
Ok, got it. At least part of it. Lines 405 and 407 in collections.grid.resources.js:
```
var elm = t.className.split(' ')[0];
if(elm == 'controlBtn') {
  var action = t.className.split(' ')[1];
```
This code expects the class names to be the first in the list of classes for the element. My icon element classes had them at the end. 
It would be better _not_ to use classes for this, but to use data-attributes like that:
```
<element data-btn="actionBtn" data-action="edit">
```
The classes can stay in the code for the styling, but triggering relys on the data-attributes.

**Comment by TheBoxer** [comment]
Hmm, looks like clicking on the icon doesn't count as clicking on the row, so row don't get selected and the hander doesn't know what to do...

**Comment by theboxer** [comment]
@inreti I think I got it working :)

**Comment by inreti** [comment]
Great work. So I can get rid of my custom renderer and use only pagetitleWithIcons!
