### ISSUE TITLE
Limitation to resource types does not work

### ISSUE THREAD

**Issue by boformer** [modxcms/Collections#146]
In the 3.x release notes you said that it is possible to limit Collections to a certain resource type, for example only modDocuments.

It only works partially: Users can only create the specified resource types when clicking on the create new child button.

But all resources are still displayed in the grid.

For example I have a collection that is limited to modDocuments. A child selection is still displayed in the grid.

**Comment by theboxer** [comment]
Yes, it's only for limiting the button used for creating new children, not for what is in the grid.

**Comment by boformer** [comment]
Are there any plans to change that?

This is somehow related to https://github.com/modxcms/Collections/issues/138

**Comment by theboxer** [comment]
No plans for changing how the field works. But if there will be enough interest in #138 this can take the ride with it :)
