### ISSUE TITLE
sort on menuindex

### ISSUE THREAD

**Issue by jenswittmann** [modxcms/Collections#147]
Hello,
i try to sort on menuindex. But it does not work since the last update (new sort option, v3.2.1).
Collections has the following Settings:

### Setting 1
<img width="943" alt="bildschirmfoto 2015-08-04 um 12 45 10" src="https://cloud.githubusercontent.com/assets/5232770/9059079/39209926-3aa7-11e5-84a3-40f1901084b2.png">

### Setting 2 
<img width="914" alt="bildschirmfoto 2015-08-04 um 12 45 15" src="https://cloud.githubusercontent.com/assets/5232770/9059081/39256bc2-3aa7-11e5-9b3e-ac3bf566355f.png">

### Setting 3
<img width="670" alt="bildschirmfoto 2015-08-04 um 12 45 30" src="https://cloud.githubusercontent.com/assets/5232770/9059080/3921c8be-3aa7-11e5-87c4-bfded40ec20e.png">

Is this a bug or did i missfigure the collections view?

Thanks for your great Plugin
Jens

**Comment by theboxer** [comment]
Hello, yes this is a bug in last version of Collections, it has been already resolved for next version.

Try to switch sort type to String, it may fix it for you..

**Comment by hugopeek** [comment]
I'm having the exact same problem after update to 3.2..

**Comment by hugopeek** [comment]
Setting String as sort type or `{"xtype":"numberfield","allowNegative":false,"allowDecimal":false}` as Editor doesn't work.

But glad it will be fixed soon then :)

**Comment by theboxer** [comment]
Yeah, sorry, string doesn't work also...

To fix it before next version will be released, you can grab changes from this commit: c0bd01144cdcdd4043f6e98bd4305b6caffa2253

**Comment by hugopeek** [comment]
Yes, found it already. Perfect for now.

Thanks John!

**Comment by jenswittmann** [comment]
Thanks John for the fast help!
