### ISSUE TITLE
[Feature request] Add action to move items to top of the grid

### ISSUE THREAD

**Issue by hugopeek** [modxcms/Collections#149]
Got this request from a client. They have a list with lots of items, which is sorted by menuindex. On occasion, they need to move an item from the bottom of the list to the top, which can be a bit of a hassle.

Might it be possible to add an action to the right-mouse menu (next to View / Duplicate etc.) to instantly put the item on top?

**Comment by theboxer** [comment]
Why they not manually change menuindex to 0?

**Comment by hugopeek** [comment]
Because that is hidden.. It would basically be a change menuindex to 0 button, yes.

**Comment by theboxer** [comment]
Thanks for the suggestion—will consider it for a future release. If you really need it urgently, you can contact me offline.
