### ISSUE TITLE
TV with yes/no dropdown is not storing 0

### ISSUE THREAD

**Issue by hugopeek** [modxcms/Collections#150]
I have a TV with simple Yes/No radio buttons, that is added in the grid as modx-combo-boolean, with this.rendYesNo as renderer.

When setting this TV to Yes with the dropdown, it works and the value is set to 1. But it won't register a No, the value just remains empty in the DB then..

**Comment by theboxer** [comment]
This is not collections problem, `modx-combo-boolean` stores value in true/false which are converted to 1/0

**Comment by hugopeek** [comment]
Ah ok. So should I use a different setting in editor column? Or is it an issue with MODX or ExtJS? There's no js errors or anything in console..

**Comment by theboxer** [comment]
That's not a problem in ExtJS, you just picked a combo box that acts this way. You can change the combobox definition or change the TV to store values in 1/0 instead of yes/no

**Comment by hugopeek** [comment]
The TV takes 1/0 values already, that's the thing.. The input option values are:

```
Beschikbaar==1||Beschermd==0
```

So the 1 is being set by the combo box, from the Collections grid, but the 0 is not..

**Comment by theboxer** [comment]
Ah, in that case, it doesn't transform true/false to 1/0 and you'll need to create custom editor
