### ISSUE TITLE
Column value erroneously saved with snippet renderer output

### ISSUE THREAD

**Issue by sepiariver** [modxcms/Collections#155]
Steps to reproduce:

1. I've only tried with a TV value. Setup a Collections View with a snippet renderer on the column.
2. Enable drag n drop OR enabled grid editor for any of the other columns.
3. Populate some resources. Then edit one of them from the grid view.
4. The value of the TV will now have the output of the snippet renderer, rather than the original value.

**Comment by theboxer** [comment]
That's unfortunately how the snippet renderer works. It bypasses the value on server side, so JS doesn't know about the replacement. So I suggest not using snippet renderer and editor together.

**Comment by sepiariver** [comment]
Ah ok thanks :D
