### ISSUE TITLE
Default resource type is being set to default after every configuration edit

### ISSUE THREAD

**Issue by pawelmil** [modxcms/Collections#156]
After editing configuration and saving, field Collection's setting "Default resource type"  is automatically changed to default value. 
Modx v. 2.3.3

**Comment by theboxer** [comment]
I'm not able to reproduce this issue.

**Comment by pawelmil** [comment]
1. change  Collection's setting: resource type to eg. selection
2. save
3. go to collection configuration  set again and change any settings but not default resource type and save 
4 after this resource ype id "document"

**Comment by pawelmil** [comment]
is document

**Comment by theboxer** [comment]
I'm still not able to reproduce.
Can you check if you have the correct value in DB for `Default children's resource type` after you first save the view?

**Comment by pawelmil** [comment]
1. I changed default resource type of abc2 conf  to selection, saved and  went into conf again
- in manager default resource type ic selection
- my db:
INSERT INTO `collection_templates` (`id`, `name`, `description`, `global_template`, `bulk_actions`, `allow_dd`, `page_size`, `sort_field`, `sort_dir`, `child_template`, `child_resource_type`, `resource_type_selection`, `tab_label`, `button_label`, `content_place`, `view_for`, `link_label`, `context_menu`, `buttons`, `allowed_resource_types`, `back_to_collection_label`, `back_to_selection_label`, `selection_create_sort`, `child_hide_from_menu`, `child_published`, `child_cacheable`, `child_searchable`, `child_richtext`, `child_content_type`) VALUES
(1, 'Blog', 'A default view that works well for blogs.', 1, 1, 1, 10, 'publishedon', 'desc', NULL, 'SelectionContainer', 1, 'collections.children', 'collections.children.create', 'original', 0, 'selections.create', 'view,edit,duplicate,publish,unpublish,-,delete,undelete,remove,-,unlink', 'view,edit,duplicate,publish:orange,unpublish,delete,undelete,remove,unlink', '', 'collections.children.back_to_collection_label', 'selections.back_to_selection_label', 'id:desc', NULL, NULL, NULL, NULL, NULL, 0),
(2, 'abc1', '', 0, 1, 1, 10, 'publishedon', 'desc', NULL, 'SelectionContainer', 1, 'collections.children', 'collections.children.create', 'original', 0, 'selections.create', 'view,edit,duplicate,publish,unpublish,-,delete,undelete,remove,-,unlink', 'view,edit,duplicate,publish:orange,unpublish,delete,undelete,remove,unlink', '', 'collections.children.back_to_collection_label', 'selections.back_to_selection_label', 'id:desc', NULL, NULL, NULL, NULL, NULL, 0),
(3, 'abc2', '', 0, 0, 1, 20, 'id', 'asc', NULL, 'SelectionContainer', 1, 'collections.children', 'collections.children.create', 'original', 0, 'selections.create', 'view,edit,duplicate,publish,unpublish,-,delete,undelete,remove,-,unlink', 'view,edit,duplicate,publish:orange,unpublish,delete,undelete,remove,unlink', '', 'collections.children.back_to_collection_label', 'selections.back_to_selection_label', 'id:desc', NULL, NULL, NULL, NULL, NULL, 0);

2. I saved again, closed conf and went into it again
-  in manager default resource type ic document
- my db:
INSERT INTO `collection_templates` (`id`, `name`, `description`, `global_template`, `bulk_actions`, `allow_dd`, `page_size`, `sort_field`, `sort_dir`, `child_template`, `child_resource_type`, `resource_type_selection`, `tab_label`, `button_label`, `content_place`, `view_for`, `link_label`, `context_menu`, `buttons`, `allowed_resource_types`, `back_to_collection_label`, `back_to_selection_label`, `selection_create_sort`, `child_hide_from_menu`, `child_published`, `child_cacheable`, `child_searchable`, `child_richtext`, `child_content_type`) VALUES
(1, 'Blog', 'A default view that works well for blogs.', 1, 1, 1, 10, 'publishedon', 'desc', NULL, 'SelectionContainer', 1, 'collections.children', 'collections.children.create', 'original', 0, 'selections.create', 'view,edit,duplicate,publish,unpublish,-,delete,undelete,remove,-,unlink', 'view,edit,duplicate,publish:orange,unpublish,delete,undelete,remove,unlink', '', 'collections.children.back_to_collection_label', 'selections.back_to_selection_label', 'id:desc', NULL, NULL, NULL, NULL, NULL, 0),
(2, 'abc1', '', 0, 1, 1, 10, 'publishedon', 'desc', NULL, 'SelectionContainer', 1, 'collections.children', 'collections.children.create', 'original', 0, 'selections.create', 'view,edit,duplicate,publish,unpublish,-,delete,undelete,remove,-,unlink', 'view,edit,duplicate,publish:orange,unpublish,delete,undelete,remove,unlink', '', 'collections.children.back_to_collection_label', 'selections.back_to_selection_label', 'id:desc', NULL, NULL, NULL, NULL, NULL, 0),
(3, 'abc2', '', 0, 0, 1, 20, 'id', 'asc', NULL, 'SelectionContainer', 1, 'collections.children', 'collections.children.create', 'original', 0, 'selections.create', 'view,edit,duplicate,publish,unpublish,-,delete,undelete,remove,-,unlink', 'view,edit,duplicate,publish:orange,unpublish,delete,undelete,remove,unlink', '', 'collections.children.back_to_collection_label', 'selections.back_to_selection_label', 'id:desc', NULL, NULL, NULL, NULL, NULL, 0);

**Comment by theboxer** [comment]
Sorry, I still don't get what issue you have. I am able to set `Default children's resource type` in collections view to anything and it persists it's value after I save it for second time (and changing a different field).

If you can record a video with explanation what's wrong, it may help

**Comment by pawelmil** [comment]
Here is a video:
https://www.youtube.com/watch?v=h6USY2PvcI0&feature=youtu.be

**Comment by theboxer** [comment]
Sorry, I still can't reproduce... If anyone else have the same issue feel free to comment with more details and how to reproduce.
