### ISSUE TITLE
Do no include Elements with isfolder=1 in the grid (handle them like pages with children)

### ISSUE THREAD

**Issue by boformer** [modxcms/Collections#158]
I think this would be a useful addition to exclude certain pages from the grid.

For example I've set up multiple independent sections on my page, with their own search page and input form:

![Tree](http://i.imgur.com/l0ZUnsC.png)

Right now I have to set the resource type of the "Search" and "Input form" to "Collection" to make them visible in the tree.

**Comment by theboxer** [comment]
The thing with pages with children is going to change soon and they will be under collections as well.

This is how collections works, they hide their children and mechanism to show hide resources in tree isn't easy enough to make it more flexible through collections.
