### ISSUE TITLE
Different collections.renderer_image_path setting for each Collection?

### ISSUE THREAD

**Issue by gadgetto** [modxcms/Collections#162]
Currently it seems we can only have a global **collections.renderer_image_path** setting which is used for all Collections.

In a current project I have multiple Collections with different purposes. To make it easier for editors I'd like to place corresponding images into different folders (one for each Collection). So having a possibility to have different settings for each Collection would be fine.

**Comment by theboxer** [comment]
Sorry, that's not currently possible. You can create different views and different renderers to make it work in your case.

**Comment by gadgetto** [comment]
Thanks, I solved it using different renderers. Thought it could be a feature request...
