### ISSUE TITLE
[Idea] Add quick update to grid items

### ISSUE THREAD

**Issue by hugopeek** [modxcms/Collections#163]
I miss the default MODX quick update sometimes (the right mouseclick popup from the menu tree).. Would it be possible / difficult to add this as a value to the Content menu items in Collections you think?

**Comment by Jako** [comment]
+1

**Comment by Jako** [comment]
Also 'Edit in a new tab/window' would be great. Because sometimes I have filtered the list and can't go back to the filtered selection with clicking on 'back to the collection'.

**Comment by inreti** [comment]
@Jako In this case it would be better to have collections store the last view in a cookie or something and use that by default when you come from "back to collection"...
I would love to have whole MODX this behaviour by the way - it is annoying that you always have to set again e.g. view mode in the file browser

**Comment by Jako** [comment]
I often use the 'open in a new tab/window' click (cmd-click on a Mac/ctrl-click in Windows) to bypass that issue. This works if the link is a real link and not only a javascript event.
