### ISSUE TITLE
Don't have Save/Cancel buttons when editing a entry

### ISSUE THREAD

**Issue by Spheerys** [modxcms/Collections#164]
Hi,

I'm running Collections 3.3.0-pl with MODX Revo 2.4.0-pl
I can create lots of new resources inside my Blog collections, but when I want to edit one of theme, I can't save it : I don't have the button and the shortcut CTRL+S don't works.

Here a capture : 
![collections](https://cloud.githubusercontent.com/assets/2228364/10057159/fc8ce5ea-623e-11e5-9b8a-4bed2c4b3d9b.png)

**Comment by Spheerys** [comment]
I have reinstalled everything (MODX and Collections) and the issue is solved.

**Comment by Spheerys** [comment]
I reopen this issue because I definitly have a bug with Save/Cancel button and the Collections Add-on
What kind of inforamtion can I give you to help you ?

**Comment by sepiariver** [comment]
Can you provide please any errors in your Dev Tools console, as well as any non-200 responses in the "network" tab of Dev Tools? That would be a good start...

Thanks,
