### ISSUE TITLE
New Default children's template not showing up 

### ISSUE THREAD

**Issue by voklee** [modxcms/Collections#166]
Hello i have installed the newest version of Modx (2.4.1-pl) and The newest of Collections. (3.3.0-pl). 
Default it installs the 'blog' collection view.
Its not possible to change the "Default children's template". It only shows (empty) and BaseTemplate.
Seems a bit like an issue posted in january 2015 : https://github.com/modxcms/Collections/issues/123 

Below screenshot:

![image](https://cloud.githubusercontent.com/assets/6873970/10133692/976552b6-65df-11e5-8ed4-514674c2234f.png)

**Comment by theboxer** [comment]
Hello,

the field shows list of available resource templates. You can choose a resource template that will be automatically used for new children in collection with this (Blog) collection's view.
