### ISSUE TITLE
Settings of Collections Resource Unavailable

### ISSUE THREAD

**Issue by hephaestoskin** [modxcms/Collections#168]
From what I see in the documentation of Collections I should have multiple tabs and quite a few settings to work with. However all I get is the standard "Resource" settings and under the Collections settings all I get is the "Collection's view" setting. Also when changing to Blog view nothing happens. This happens when I create a new collection in the tree or when changing a resource type.

![collections settings](https://cloud.githubusercontent.com/assets/1477468/10586172/ed422a30-7668-11e5-8a4f-6510f3dcfef3.png)

This is my log error when switching resource types: "[2015-10-19 12:19:02] (ERROR @ /manager/index.php) Instantiated a derived class CollectionContainer that is not a subclass of the requested class modDocument"

Modx version: 2.4.2-pl

**Comment by theboxer** [comment]
Settings are available from menu -> `Collection views`. In resource you can just override used view for current resource.

**Comment by hephaestoskin** [comment]
Oh well, I'm quite clearly not as bright as I thought lol. Thanks!
