### ISSUE TITLE
Collections onDocFormSave interfering with Autofoldertron

### ISSUE THREAD

**Issue by pdincubus** [modxcms/Collections#170]
Collections seems to be overwriting properties that are correctly set in the autofoldertron plugin onDocFormSave.

[Line 163](https://github.com/rckt/autofoldertron/blob/master/autofoldertron.php#L163) sets the parent ID, and if logged at this point the parent ID is correct. When logged after the ->save() it has been reset to the wrong parent. If Collections is disabled, this behaviour does not occur and the autofoldertron new parent ID is correctly retained.

**Comment by theboxer** [comment]
Update the autofoldertron plugin to run after the one from collections. If that will not help, I have no clue how to help you.
