### ISSUE TITLE
[Question] How to show Image+ images in grid?

### ISSUE THREAD

**Issue by hugopeek** [modxcms/Collections#171]
When the output of an Image+ TV is set to Default, the output is a JSON string with some values. Rendering the image using a custom Collections renderer doesn't work then anymore:

```
<div class="imageRendererTestimonialCompany"><img src="http://site.com/assets/uploads/img/testimonials/companies/{
  " sourceimg":="" {="" "src":="" "img_9100.jpg",="" "width":="" 1280,="" "height":="" 960,="" "source":="" 9="" },="" "crop":="" 1281,="" 767,="" "x":="" 0,="" "y":="" 146="" "targetwidth":="" "targetheight":="" "alttag":="" false="" }"="" width="100"></div>
``` 

This is the JS to render the image:
```
var imageRendererTestimonialCompany = function(value, metaData, record, rowIndex, colIndex, store) {
    if (value != '' && value != null) {
        var baseUrl = MODx.config.default_site_url + "testimonials/companies/";
        if (value.indexOf('http://') === 0) {
            baseUrl = '';
        }
        return '<div class="imageRendererTestimonialCompany"><img src="' + baseUrl + value + '" width="100"></div>';
    }
}
```

The src key probably needs to be isolated from the value, but I can't quite figure out how to do that.. Does anyone have an idea?

**Comment by inreti** [comment]
There is a MIGX renderer coming with ImagePlus which can be used in collections as well.

**Comment by hugopeek** [comment]
Wow, that's perfect. Even eliminates the need for separate renderes for different image folders..

Many thanks @inreti!
