### ISSUE TITLE
Uncaught SyntaxError: Unexpected token }

### ISSUE THREAD

**Issue by Gliba** [modxcms/Collections#173]
Somthing wrong with extjs after update from 3.1.1 to 3.3.0. Its wired some collections work others not.

![image](https://cloud.githubusercontent.com/assets/1550782/11078315/5fbdcb34-8805-11e5-8046-86521b9a4631.png)

**Comment by theboxer** [comment]
Please click on the link on right side (line number), you should see more about the error and post it here please.
