### ISSUE TITLE
Listing Selection Container with GetResources

### ISSUE THREAD

**Issue by HarveyEV** [modxcms/Collections#179]
I have several selection containers I would like to list with getResources. Is there a way to do that? Maybe by the resourceType? I haven't been able to find any options for getResources that would let me include selection type resources.

**Comment by theboxer** [comment]
All resource types are included in output of getResources, unless you set otherwise. If you want to show only list of Selection Containers, you can include a where option to your getResources call:
```
&where=`[{"class_key": "SelectionContainer"}]`
```
