### ISSUE TITLE
Remove Heading colors from the mgr.css

### ISSUE THREAD

**Issue by gmclelland** [modxcms/Collections#181]
I think this would look better with the default modx theme.

Before:
![with](https://cloud.githubusercontent.com/assets/40570/12057784/43217c10-af0a-11e5-9bb3-c2a854a75fd9.jpg)

After:
![without](https://cloud.githubusercontent.com/assets/40570/12057789/4e00c78a-af0a-11e5-9248-4622f096f970.jpg)

What do you think?

**Comment by theboxer** [comment]
I think it's covered by #177
