### ISSUE TITLE
getSelections sorting by menuindex does not work

### ISSUE THREAD

**Issue by jcamachott** [modxcms/Collections#182]
Hi,

Sorting by pagetitle works fine, both ASC and DESC....but not menuindex.

The item with menuindex = 4 is sorted as the first item.

See screenshot: 
![2016-01-04_20-40-54](https://cloud.githubusercontent.com/assets/1188776/12104619/95b372a4-b323-11e5-8b18-71b67eb37690.png)

My getSelections call:

     [[!getSelections? &selections=`459` &limit=`0`  &tpl=`linksList.tpl` &sortby=`menuindex` &sortdir=`ASC` ]]

Thanks.

**Comment by theboxer** [comment]
Don't pass ``` &sortby=`menuindex` ``` and it will work as you expect.
When you pass any value to `&sortby` the getSelection snippet will pass it to getResources, which will result in sorting by any given resource field. In your case it's sorting by resource's menuindex, not by menuindex of the selection item.

**Comment by jcamachott** [comment]
Ah...thanks a lot...might be a good idea to put that in the docs.



Regards
John

John Camacho | (868) 374 6507 | john@pixelstation.com | Skype: johncamachott
*Expert mentor at Codementor.io* | http://goo.gl/8G5VOo
