### ISSUE TITLE
Endless loading of the manager page with Collections 3.4.0

### ISSUE THREAD

**Issue by berj** [modxcms/Collections#185]
I just update Collections 3.3.0 to Collections 3.4.0.

When I click on the Collections Icon in the ressources tree, it causing an endless loading of the manager page and I cannot acces to the collectionContainer.

One thing, for my installation the core is out of the root. Is this may be the cause?

Modx 2.4.2
Collections 3.4.0
PHP : 5.5.31
mysql : 5.5.47

Thanks for your help

**Comment by theboxer** [comment]
Anything in MODX error log in or JS console?

**Comment by berj** [comment]
Thank you for responding so quickly.

No nothing in the MODX error log and for the moment I don’t see error in the JS Console.

The problem appears on Safari Version 9.0.3

I made some test and Collections 3.4.0 work fine : 

- Chrome (Version 46.0.2490.86 (64-bit))
- Firefox 42.0
- Internet Explorer 11
