### ISSUE TITLE
Show resource containers still in tree

### ISSUE THREAD

**Issue by christianseel** [modxcms/Collections#186]
It would be nice to have a system setting that specifies wether resource containers should stay in the resource tree or should be hidden in tree and displayed in the collection view.

In my case I have many use cases where containers should stay in the tree and only docuements should be in the collection view…

**Comment by digitalpenguin** [comment]
Or even resources which are not containers. 
Perhaps a "show in tree" check-box added to the settings of each resource that is a child of a collection.

**Comment by funkyduke** [comment]
It is a little bit confusing for the user when a collection inside a collection is outside the grid. So please make the collections also displayed inside the grid.

**Comment by theboxer** [comment]
Duplicate of #250
