### ISSUE TITLE
Aesthetic issue with Collections.renderer.pagetitleWithButtons

### ISSUE THREAD

**Issue by hexcollective** [modxcms/Collections#188]
Stylistic issues with Collections: 3.4.1-pl
Title dropping down onto 2nd line.

![screen shot 2016-02-02 at 17 55 04](https://cloud.githubusercontent.com/assets/692359/12758903/6af45e92-c9d6-11e5-88bb-0f6da34dede0.png)

**Comment by gadgetto** [comment]
Can confirm this!

**Comment by hexcollective** [comment]
Me 3! oops :/

**Comment by theboxer** [comment]
feel free to submit PR with style fixes :) that's out of my range

**Comment by hexcollective** [comment]
Sorry not sure how to do the PR though this does the trick ~
`.collections-grid .main-column a { float: none }` mgr.css line 123

**Comment by sebastian-marinescu** [comment]
Hey @theboxer I created at fix for that issue – had any time looking at it?

**Comment by neoneddy** [comment]
+1

**Comment by sepiariver** [comment]
Fixed with merged PR: 010498510b0efd8719e5d77c5ed80ae2a23280b6
