### ISSUE TITLE
Feature Request: Next and Previous Buttons

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/Collections#190]
Have "Next Resource" and "Previous Resource" buttons when editing a resource within a collection so the user doesn't need to keep going back to the list.

**Comment by inreti** [comment]
+1

**Comment by theboxer** [comment]
Next and prev resource highly depends on your sorting preferences in collection's view and on your current children's table, where you can change the sorting by clicking on column headers. Querying next & prev resource could be quite expensive operation and could lead to significant slowdown when loading any resource. So this won't be implemented.
