### ISSUE TITLE
Lost some collection settings during update

### ISSUE THREAD

**Issue by Jako** [modxcms/Collections#196]
After the last Collections update, the 'selections' on that page have lost their resource type (they were changed back to Document) and the 'collections' views settings have been switched to the 'default view'.

**Comment by theboxer** [comment]
That's weird, there's no code for switching selections back to resource and changing views on upgrade...

**Comment by Jako** [comment]
Hmm, any Idea how this could happen? I have reverted the 3.4.0 update because of some incompatibilities there. But in between there was one update to 3.4.1. Could the 3.4.0 state be saved and applied again during a second update somehow?.
