### ISSUE TITLE
Collection's view reset if quick update resource

### ISSUE THREAD

**Issue by gravino81** [modxcms/Collections#200]
If set in my Collection the "Setting > Collections > Collection's view" with my personal view, when i modify this resource with "quick update" the Collection's view is reset to (use default view)

![screen](https://cloud.githubusercontent.com/assets/5929863/15100603/82548c7e-1576-11e6-818c-2a0d4164ce7b.png)

**Comment by vierkantemeter** [comment]
Why isn't this pushed in a new version of Collections?
