### ISSUE TITLE
Icons for list items displacement in Safari since 3.5.0

### ISSUE THREAD

**Issue by gadgetto** [modxcms/Collections#206]
Just updated to 3.5.0 and now the icons for list items are in a separate line:

<img width="320" alt="screenshot 2016-08-01 21 00 02" src="https://cloud.githubusercontent.com/assets/876737/17305605/72d687f0-582b-11e6-8493-249b222ae8f2.png">

Problem exists in Safari. Works like expected in Chrome. Didn't test other browsers.

**Comment by theboxer** [comment]
I'm not having this issue with Safari and 3.6.0
