### ISSUE TITLE
upgrade to 3.5 cannot edit child page, renders blank

### ISSUE THREAD

**Issue by nanibear** [modxcms/Collections#208]
Using Collections 3.5 with Articles 1.7.11, the upgrade left all child pages unable to edit, just a blank screen. I tried reinstalling 3.5 and even reinstalled 3.4.2 with no positive results.

**Comment by navtsi** [comment]
same for me on every installation. I have different problems with different installtions. Some are completely blank, some didn't show only the list. I tried to reinstall, clear cache on server. Now I have an installation I'll get a fatal error after uninstalling 3.5.

**Comment by ckburnett** [comment]
I can confirm the same thing on one installation (haven't tried others), and there's another report in the forums:
(https://forums.modx.com/thread/100644/collections-3-5-update-rendering-blank-pages-in-manager)

In my case, the environment was Revo 2.5.0 Advanced, Collections 3.5.0

I reverted Collections to the previous version and was successful in getting it to work again with the old version.

**Comment by navtsi** [comment]
In one of my installations I reconfigure all collection templates with new renderers, and it works. Cannot verify all my other installations, but for this this one it works.

**Comment by theboxer** [comment]
@nanibear @navtsi @ckburnett Hello folks, could you please try and install the attached version (3.5.1) if it will resolve issue you are having? If you see a blank page try to reload the page and clear cache (browser cache - old JS might still be there).

[collections-3.5.1-pl.transport.zip](https://github.com/modxcms/Collections/files/447416/collections-3.5.1-pl.transport.zip)
