### ISSUE TITLE
Different image renderer path problems

### ISSUE THREAD

**Issue by navtsi** [modxcms/Collections#210]
Hi,

I love collections but I have some problems with the image renderer:

1) I'm using Babel to create multi language pages. In this case alway the cultureKey is in the front of the image path, but I need it without /de or /en in front of the path.

2) And additionally I working very often with media sources. In the imageTV only the filename will be stored. How to integrate the media source path in the image path?

3) The last problem ist an image+ specific issue. The image+ TV value is a json object like this
`{
  " sourceimg":="" {="" "src":="" "bavaria_club_almchalet.jpg",="" "width":="" 800,="" "height":="" 301,="" "source":="" 8="" },="" "crop":="" "x":="" 244,="" "y":="" 0,="" 301="" "targetwidth":="" 245,="" "targetheight":="" 0="" }`
 So how to parse? 

Sorry I'm not a developer and not so familiar with Javascript and PHP.

Thanks

**Comment by LexDonowan** [comment]
3. For image plus you can use a renderer from migx – ImagePlus.MIGX_Renderer

**Comment by theboxer** [comment]
You'd need a custom renderer tailored to your case, either a snippet renderer or JS renderer.
