### ISSUE TITLE
Collection's view reset if quick update resource

### ISSUE THREAD

**Issue by vierkantemeter** [modxcms/Collections#213]
This problem is still here, even after update to 3.5.0.
Related: https://github.com/modxcms/Collections/issues/200

MODX 2.5.0

**Comment by theboxer** [comment]
Can't reproduce.

**Comment by vierkantemeter** [comment]
That's weird.. If you want to take a look at my install, you're welcome.

**Comment by theboxer** [comment]
Sure, send me creds please

**Comment by theboxer** [comment]
Closing due to long inactivity.
