### ISSUE TITLE
CTRL/CMD click child to open in new window

### ISSUE THREAD

**Issue by brain2002** [modxcms/Collections#214]
In previous versions you could do CTRL/CMD click on a child item to quickly open in a new tab. Because the click is now a javascript link that function is broken.

A real bummer because if I had to edit 10 pages I would quickly open them in new tabs => edit => save and close.

Is this something that could be reintroduced? Maybe an "Open in tab" button?

Thanks! :)

**Comment by theboxer** [comment]
Added with recent commit, will be included in next release.
