### ISSUE TITLE
Upgrading MODX to 2.5.2 breaks Collections Image Renderer

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/Collections#220]
Tested now on 3 sites.

Collections version 3.6.0
MODX version 2.5.2

All images rendered in a Collections grid are now broken after upgrading MODX core to 2.5.2
Img src now shows undefined.
e.g. 
`/undefinedassets/images/blog/Blog Post 7.jpg`

In this case, my Collections.render_image_path setting is: {assets_url}content/
This was working until upgrading to 2.5.2

This hacky workaround fixes the issue for the above case:
`Collections.renderer.image = function(value, metaData, record, rowIndex, colIndex, store) {
    if (value != '' && value != null) {
        //var imgPath = MODx.config['collections.renderer_image_path'];
        //return '<img src="' + MODx.config.base_url + imgPath + value + '" width="64">';
        return '<img src="' + MODx.config.base_url + 'assets/images/' + value + '" width="64">';
    }
};`
Note I have hardcoded the value.

Update: Actually, it doesn't even need to be the latest version of Collections. I just updated a site to MODX 2.5.2 where the version of Collections was only 3.4.2 and the same thing happened.

MODx.config['collections.renderer_image_path'] is coming through as undefined.

**Comment by dubrod** [comment]
I confirmed same error, but before upgrading to MODX 2.5.2

`MODx.config['collections.renderer_image_path'] is coming through as undefined.`

**Comment by berj** [comment]
Modx 2.5.2
Collections 3.6.0
PHP 5.6.28

I got the same problem with the original config.js.php file and with the modified file (_Remove path related settings from MODx.config, reverting part of #13170_)

All I see in the grid it is the path _(assets/images/produits/monimage.jpg_)  of the image instead of the rendered image.

Thank for your help

**Comment by theboxer** [comment]
This is MODX issue, as @Mark-H referenced.
