### ISSUE TITLE
Drag and Drop Sorting Not Working

### ISSUE THREAD

**Issue by nickff** [modxcms/Collections#222]
Hello,

First off thanks for the great plugin and all the hard work. Really appreciate it.

Secondly, I'm using Collections 3.6.0 on a new project and am looking to employ the new drag-and-drop feature for sorting the grid. The issue is that no matter where I drag a resource, after the "loading" message disappears the dragged resource always ends up going into the first position (and resorting below that in a strange manner). _Directly_ after the drag it's correct, but then the "loading" message appears and after that it does it's own thing.

Attached are my settings for the view. Perhaps I'm missing something there? Let me know!

![screen shot 2017-01-02 at 3 06 37 pm](https://cloud.githubusercontent.com/assets/386558/21597291/38ec3ee0-d0fd-11e6-8fa7-91656d8a0671.png)

**Comment by theboxer** [comment]
Could you add menu index column to the children's grid and send a screenshot with the children's grid please?

**Comment by nickff** [comment]
Adding the "menuindex" column looks to have resolved the issue. Thanks so much!
