### ISSUE TITLE
publish dates

### ISSUE THREAD

**Issue by funkyduke** [modxcms/Collections#223]
For a blog it would ben interesting to have the 'select-a-date' (publishedon) field on the mainpage of the article and not under the settings. In that way you can hide the settings tab from the user. 

I believe this was the case with 'Articles'.

**Comment by sepiariver** [comment]
Hi @funkyduke 

Thanks for using Collections and MODX :)

Collections, as an Extra, deals exclusively with the parent Resource—the Collection. Child Resources are essentially un-modified by Collections, so the feature request you're referring to here is outside the scope of Collections.

You can almost accomplish what you want to do with the MODX core feature "Manager Customizations" but standard Resource fields currently cannot be moved around, only renamed. I'll submit a Feature Request and cc you on it, so you can keep abreast of when this becomes a supported feature.

Thanks again.
