### ISSUE TITLE
Drag & Drop doesn't fire 'OnResourceSort' event

### ISSUE THREAD

**Issue by dannevang** [modxcms/Collections#226]
It would be good if the event 'OnResourceSort' would be fired when you drag and drop in a collection, making collections work with plugins working with that event.

Tested on MODX Revo 2.5.4 and Collections 3.6.0-pl

**Comment by labr1005** [comment]
Any plans to fire "OnResourceSort" or a new custom Collections event when drag and dropping?

**Comment by theboxer** [comment]
We can do a custom one for it.
