### ISSUE TITLE
Error unlinking Selection

### ISSUE THREAD

**Issue by johnmacdonald3000** [modxcms/Collections#227]
I'm getting the following error when unlinking a Selection: **collections.selection_err_nfs**

The Selection stays in place. The only way I've found to remove it is to delete the resource.

MODX: 2.5.5 / Collections 3.6.0

**Comment by theboxer** [comment]
I'm sorry, I can't replicate this issue. Feel free to reopen with more details.

**Comment by azeller** [comment]
I am having the same issue unlinking. This has happened during a MODX upgrade. I think it might have to do with MySQL under the hood. A lot of things have been upgraded in our case. We upgraded to PHP7, MODX 2.6.1 and lots of other things, so this will be hard to narrow down. If you need logfiles or something, I am still having the issue as we speak on one of our demo-pages.
