### ISSUE TITLE
View's settings are not retained after save

### ISSUE THREAD

**Issue by kinaz** [modxcms/Collections#230]
Hi,

sometimes when a view is saved, its settings are not retained; if view page is reloaded settings are not correct.

Ex.:

default resource type for children: Static resource is chosen
default content type for children: JPG is chosen
View is saved
View page is reloaded and the 2 settings above are not retained (apparently the default value is assigned)

Regards

**Comment by theboxer** [comment]
I can't reproduce this issue. Feel free to reopen with more details.
