### ISSUE TITLE
Unpublishing doesn't trigger refresh

### ISSUE THREAD

**Issue by matdave** [modxcms/Collections#231]
When using Collections.renderer.pagetitleWithButtons, if you click "Unpublish" it doesn't look like it does anything.  If this could somehow trigger a grid refresh, it would be much clearer to the user.

**Comment by theboxer** [comment]
It triggers a refresh...

**Comment by matdave** [comment]
Ahh... it's StaticCache that is causing a 500 error and preventing the refresh on unpublish. I updated the code for that plugin and it now refreshes.
