### ISSUE TITLE
Creating & Updating Fails because redeclaring classes

### ISSUE THREAD

**Issue by robotjoosen** [modxcms/Collections#234]
The require_once in collectioncontainer.class.php redeclares modResourceCreateProcessor and modResourceUpdateProcessor. By changing line 2-4 to check if they are already declared the issue is fixed.

Not sure if this is the best way to do it, but it worked for me.

```
if (!class_exists('modProcessor')) require_once MODX_CORE_PATH . 'model/modx/modprocessor.class.php';
if (!class_exists('modResourceCreateProcessor')) require_once MODX_CORE_PATH . 'model/modx/processors/resource/create.class.php';
if (!class_exists('modResourceUpdateProcessor')) require_once MODX_CORE_PATH . 'model/modx/processors/resource/update.class.php';
```

**Comment by theboxer** [comment]
@robotjoosen Please check if your server has APC installed. If so please check `include_once_override` setting.
