### ISSUE TITLE
Sub Collections

### ISSUE THREAD

**Issue by pepebe** [modxcms/Collections#238]
As far as I can tell any child resource with the class_key "collection" is visually removed from the collections grid.

Is there an obvious reason for this, or is this just a design decision?

If its a design decision, can we make this optional?

I'd like to have the option to display "sub"-collections inside the grid.

Cheers,

pepebe

**Comment by theboxer** [comment]
The grid can't change it's settings based on View of the sub-collection, which would allow only sub-collections of same view - which would make them useless as you can achieve same thing just by normal resources.

**Comment by pepebe** [comment]
Hi,

thanks for your fast response.

I guess I understand your reasoning, but I don't agree with your conclusion.

If I click "view", I see the exact same grid for a resource with children of its own as for the parent resource. This may make sense in a few cases, but I guess most of the time it doesn't.

As a solution, a sub grid would be a great. After clicking the "view" action, the subgrid settings should be displayed depending on the template of the resource. Using the default one if there is none defined.

If this is not feasible, there is already an option to remove "view" from the collections settings. 

Apart from the view feature, I don't see any reason why the a child collection should not appear inside the parent collection.

Here is my use case:

- Branches (collection)
- - Branch 1 (also a collection)  - A couple of TVs with contact data, etc can be easily reviewed and changed by the grid.
- - - Opening Hours (document with a special contentblock)
- - - Features (document)
- - - Gallery (moregallery)
- - - Map (map)
- Branch 2 (collection)

It would b e great, if child collections wouldn't be removed from the grid by default or if there would at least be an setting to keep them if needed.

**Comment by jchirschy** [comment]
It might be an issue with sub collections. Sub collections are removed from the grid view.

By reading documentation, I thought Sub collection and nesting were supported. The parent collection does not list children that are themselves collection in the grid but only in the tree. Is it the correct behaviour  or did I miss something ?

Thanks in advance
