### ISSUE TITLE
How to get id inside a "non" id grid column

### ISSUE THREAD

**Issue by pepebe** [modxcms/Collections#239]
I want to fill a collumn with gallery thumbnails.

The thumbnails will be create by a snippet that needs the id of the resource.

For some reason I can't add a second "id" colum to the grid, so I need to get the value from something else.

Any advice?

**Comment by theboxer** [comment]
Use a snippet renderer?

**Comment by pepebe** [comment]
Sorry, I didn't see the proverbial elephant in the room.

I thought standard fields only return the value of the of the field at $scriptProperties['value'], but they also have a scriptProperties['row'] array listing all other variables of that resource. 

So is can use longtitle to add a new column, label it thumbnails, use a snippet renderer, grab die id from $scriptProperties['row']['id'], an create my thumbnails with $modx->runSnippet();

Awesome!

Thanks for making this so easy.

Patrick
