### ISSUE TITLE
Duplicating Items

### ISSUE THREAD

**Issue by pyrographics** [modxcms/Collections#241]
Duplicating items should give the duplicate a new publish date and unique menu index.  Currently it keeps it the same as the original but this causes issues with sorting when using duplicate as a template for a new listing.  Mainly when every item in a list is created by duplicating, and sort is by menuindex, drag and drop in the list does not function correctly.

**Comment by theboxer** [comment]
Collections are using core duplicate processor, so it acts just like it does in core.
