### ISSUE TITLE
Unpublishing a resource also deletes the unpublish date

### ISSUE THREAD

**Issue by pepebe** [modxcms/Collections#242]
**Problem:**
Unpublishing or publishing a resource in a collection by pressing the "unpublish/publish" button changes the values of both the published_on AND the unpub_date field.

**Expected behaviour:**
Only the value of the publishedon field is changed. The unpub_date fields remains untouched.

This is also the exact same behavior of  "edit resource" and "quick edit"

Version:
MODX 2.5.7 and Collections 3.6.0-pl, Latest Chrome, Ubuntu 16.4 LTS

**Comment by theboxer** [comment]
This is expected behaviour as it's same as publish/unpublish actions from context menu on the resource tree.
