### ISSUE TITLE
Not save change in modx-combo-boolean width TV default value

### ISSUE THREAD

**Issue by gravino81** [modxcms/Collections#246]
If I setting a TV Single select Yes/No (Yes==1||NO==) and the TV have "default value = 1", in collection view (Editor: modx-combo-boolean and Render this.rendYesNo) not save de change.

If I remove de "default value = 1" at the TV, in collection view save correctly, but width default value don't work.

Modx version 2.5.8-pl
Collections version: 3.6.0-pl

**Comment by theboxer** [comment]
Hello, this is not a Collections issue.
You are using modx-combo-boolean which sends true/false which you can't use without a server side processing where it would transform string "true" and "false" to proper boolean.

I'd suggest creating own combo box with 1/0 values.
