### ISSUE TITLE
No way found to enter data into new columns/fields of child documents 

### ISSUE THREAD

**Issue by shinyiee** [modxcms/Collections#249]
Reading through all issues in this forum, my question seems odd. But I spent hours already and just don't get it. The solution must be very ease...

I have installed:

online: modx revo 2.6.0-pl und Collections 3.6.0-pl
locally: modx revo 2.4.3-pl und Collections 3.6.0-pl

In Collection views I created a new view (a copy of blog):
![image](https://user-images.githubusercontent.com/34608767/34074004-caa4c6a2-e2a6-11e7-8773-142a5d6efe94.png)

In here I created new columns test, tv_testtv and testtv (position.1, 2 and 3).
![image](https://user-images.githubusercontent.com/34608767/34074039-58230944-e2a7-11e7-9b1c-a3dfc20c24be.png)
As "Default for templates" I tried blank and "BasisTemplate" - it didn't matter. Actually it is BasisTemplate.

As you can see one of the new columns refers to a Template-Variable (tv_testtv), which works fine by the way.

Then I created a document (as container), ressource typ = collection,. Template is BasisTemplate (which refers to the working Template-Variable). I saved it and the grid appeared. So far, so good.

![image](https://user-images.githubusercontent.com/34608767/34074217-9663239e-e2aa-11e7-927f-01dc58a26678.png)

But as you can see there is no data in columns test and testtv, because there is no form to find that allows data entry. It was my understanding, that an registry would appear with the necessary form fields - like for Template-Variables:

![image](https://user-images.githubusercontent.com/34608767/34074518-39d98c2e-e2b1-11e7-91e2-13996a67610f.png)

At least, data entry should be possible within the grid, like it is for menu-index. But it's not. Maybe it would, if there were data in the first place, who knows.

To investigate this further, I installed Blogit as well, only to find out, that they work with Template-Variables and no additional columns in the collection view. So as attandant questions allow me to ask: what's the difference and what is preferable? And what are those columns/fields anyway if not Template-Variables?

Funny enough, that not one of those (only russian) youTubes I watched showed how to use the created fields and enter data.
Please, get me started and tell me what's wrong - and what's right.

Thanks.

**Comment by theboxer** [comment]
Hello,

You can't just add non-existing fields to columns. Collections won't provide you any kind of edit view on those. The columns definition is there to provide you a customised grid for your resources, where you can include columns from modResource (+ TVs, + Tagger) that you'd like to have fast access to / see in the grid.
