### ISSUE TITLE
Selections should be able to be nested in a Collection

### ISSUE THREAD

**Issue by neoneddy** [modxcms/Collections#251]
I have a use case, where we're using a Collection for 60-70 Landscape Design Projects, we want to have 10-12 sub-collections.   A Selection would be a perfect use case of these, except when I nest a Selection in a Collection it disappears from the Tree.

**Comment by FerX** [comment]
https://github.com/modxcms/Collections/issues/250

**Comment by nickff** [comment]
*bump

**Comment by theboxer** [comment]
That's correct behaviour. It disappears from the tree and appears in the collection. Feel free to reopen with more details.
