### ISSUE TITLE
Default Template for Child Ressources not working

### ISSUE THREAD

**Issue by tjventurini** [modxcms/Collections#252]
Hey there :smiley: 
Trying to use the Standard-Template for Childressources (_Standard-Template für Unteressourcen_ in German) but it is never used as default. No matter to which template I set the default, it is never used when I create a new child ressource.
PS: Great extension anyways! :+1:

**Comment by theboxer** [comment]
I can't reproduce your issue, child template is used fine here. Feel free to reopen with more details.
