### ISSUE TITLE
Make Collections compatible with MODX 3

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/Collections#253]
Installing Collections breaks the installation of MODX 3 (dev).

The error is: Fatal error: Declaration of CollectionContainer::getControllerPath(xPDO &$modx) must be compatible with modResourceInterface::getControllerPath(&$modx) in /home/vagrant/code/modx3/public_html/core/components/collections/model/collections/collectioncontainer.class.php

MODX3 doesn't allow type hinting for the parameter yet 2.6.x requires it.

**Comment by digitalpenguin** [comment]
Changing `getControllerPath(xPDO &$modx)` to `getControllerPath(&$modx)` fixes the problem for MODX3 but breaks compatibility with MODX 2.6.x

**Comment by theboxer** [comment]
The 3.x compatibility will be sorted out once 3.x will approach release.
