### ISSUE TITLE
Change to not break open in new tab functionality

### ISSUE THREAD

**Issue by qodo** [modxcms/Collections#255]
When viewing a collection the Title and buttons that appear in the column using the renderer `renderer.pagetitleWithButtons` break **ctrl-click/cmd-click** actions meaning you can't easily open them in a new tab like you can other other areas of MODX.

![collections-screen](https://user-images.githubusercontent.com/3908836/40244894-0a36114e-5abc-11e8-8219-25c26b7271e7.jpg)

Would it be possible to change this so that I can ctrl-click to open/view/edit the resource in a new window/tab?

Thanks,

**Comment by theboxer** [comment]
They are using `a` tags in 3.6.0 so cmd+click is possible
