### ISSUE TITLE
Feature Request: Make collection resources searchable from main dashboard search bar.

### ISSUE THREAD

**Issue by bloodcrow777** [modxcms/Collections#261]
One thing that I've noticed is that you can't find resources that live inside of a collection, from the main search bar at the top left of the modx dashboard. 

Would love if this was included in some way in order to track down pages more easily, without having to drill down into a collection, that may or may not be buried inside of another directory / resource. So sometimes tracking things down gets very tedious.

**Comment by theboxer** [comment]
I can reproduce this issue. Please feel free to reopen with more details.
