### ISSUE TITLE
"Open" breadcrumb

### ISSUE THREAD

**Issue by EkoOne** [modxcms/Collections#269]
The screenshot pretty much sums up the issue. When hovering over the last crumb the blue background shows a weird white "shape" which pushes both the text and arrow upwards so it's no longer vertically centered.

![modx-collections-breadcrumb](https://user-images.githubusercontent.com/1754223/51945966-d59f9880-23e5-11e9-8505-5635b69f879c.png)

**Comment by matdave** [comment]
This will be fixed in the next release. Thanks for reporting.
