### ISSUE TITLE
Parent Page Heading Small

### ISSUE THREAD

**Issue by EkoOne** [modxcms/Collections#273]
Revo 2.7.1
Collections 3.6.0

This issue only seems to happen on Collection parent pages. Child pages and other (non-Collection) Manager pages all render fine.

As the screenshot illustrates the heading text (“Tutorials”) on a Collection parent page is too small.

![modx-collections-heading](https://user-images.githubusercontent.com/1754223/53355033-c3821e80-38ed-11e9-8861-8e46aec359b5.png)

**Comment by devlanda** [comment]
@EkoOne Solved this issue with #274 and #275.
