### ISSUE TITLE
Using MIGX for Image Thumbnail 

### ISSUE THREAD

**Issue by crimsonpixel** [modxcms/Collections#278]
To enable the inclusion of multiple images for a product I am using MIGX.  How is it possible to add the getImageList snippet to run to display the first image as a thumbnail in the Collection view.

I am guessing I would need to create a snippet to run the that snippet but as my knowledge of PHP is limited, I am not sure where to start...

**Comment by theboxer** [comment]
You'll need to create a snippet and put it as a snippet renderer on a column. In that snippet you call ```php
$properties = []; // array of properties you want to pass in
$modx->runSnippet('getImageList', $properties);
```
