### ISSUE TITLE
[Fred Plugin] Collections type suggestion

### ISSUE THREAD

**Issue by JANogueira** [modxcms/Collections#283]
Hi,

While testing the Collections 3.7.0 with Fred, I found that it is only possible to create pages as documents.

Is there any plan to allow other type of collections, like Symlink resources or Weblink resources to allow easier lists building directly from the front end?

Thanks

**Comment by theboxer** [comment]
It's actually possible only to create pages as documents and only as Fred documents. There's no plans on expanding this any further as you won't be able to manage these from Fred anyways.
