### ISSUE TITLE
Add Portuguese language to Croudin

### ISSUE THREAD

**Issue by JANogueira** [modxcms/Collections#284]
Please add Portuguese language to Croudin so I can help you with the translation.

Thanks.

**Comment by JANogueira** [comment]
@theboxer, please don't forget about this so I can translate on time for the new release.
Cheers

**Comment by theboxer** [comment]
Added, thank you!

**Comment by JANogueira** [comment]
Translation finished ;)

**Comment by theboxer** [comment]
You're a rockstar!
