### ISSUE TITLE
Unknown column 'CollectionTemplate.show_quick_create' in 'field list'

### ISSUE THREAD

**Issue by Spheerys** [modxcms/Collections#295]
Hello,

After upgrade to Collections 3.7.0 my views stop working, but I don't remember the error :(
I had delete and reinstall Collections 3.7.0 and now my vues disapears and I can't recreate them.
I get this error on my browser :
```

Fatal error: Uncaught Error: Class 'IndexManagerController' not found in /home/hedy/Sites/domain.com/core/model/modx/modmanagerresponse.class.php:190 Stack trace: #0 /home/hedy/Sites/domain.com/core/model/modx/modmanagerresponse.class.php(78): modManagerResponse->instantiateController('IndexManagerCon...', 'getInstanceDepr...') #1 /home/hedy/Sites/domain.com/core/model/modx/modmanagerrequest.class.php(187): modManagerResponse->outputContent(Array) #2 /home/hedy/Sites/domain.com/core/model/modx/modmanagerrequest.class.php(135): modManagerRequest->prepareResponse() #3 /home/hedy/Sites/domain.com/manager/index.php(59): modManagerRequest->handleRequest() #4 {main} thrown in /home/hedy/Sites/domain.com/core/model/modx/modmanagerresponse.class.php on line 190
```
On the MODX log, I have this error :
```
[2019-08-26 18:32:10] (ERROR @ /home/hedy/Sites/domain.com/core/xpdo/om/xpdoobject.class.php : 240) Error 42S22 executing statement: 
Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'CollectionTemplate.show_quick_create' in 'field list'
)
```
I don't know why my views disapears and I I can get them back, but I really need to at meast rebuilt them !

**Comment by Spheerys** [comment]
up :)

**Comment by theboxer** [comment]
Try and clear modx & browser cache.

For the second error, seems like your db wasn't updated correctly (I'd guess some env issue). You'll have to create `show_quick_create` column in the `CollectionTemplate` table. Install collections on a fresh site and check the column definition there.

**Comment by 5koder** [comment]
I fixed this error by uninstalling this extra:
https://modx.com/extras/package/statusoverrideips
