### ISSUE TITLE
3.7.0 menuindex edits via grid not saved

### ISSUE THREAD

**Issue by travisbotello** [modxcms/Collections#297]
With version 3.7.0 menuindex edits via grid (inline editing) are not saved.

Steps to reproduce:

- create collection
- add 2-3 child resources
- alter menuindex via grid
- save the collection
- reload the collection 
=> menuindex values were not saved

MODX 2.7.1
Collections 3.7.0
PHP 7.3

Issue doesn't occur in version 3.6.0

**Comment by tonyklapatch** [comment]
I'm also getting this error on 3.7.0. This error is being logged in the JS console, no request is being sent to the server.

![image](https://user-images.githubusercontent.com/11136895/64475770-123e2a00-d155-11e9-9b39-a60573440f7e.png)

**Comment by mit0787** [comment]
I have same problem not only for menuindex but for all editable fields

**Comment by travisbotello** [comment]
We reverted to 3.6.0 in our production installations.

**Comment by JoshuaLuckers** [comment]
This issue also affects other grid editors (combo, custom etc).

**Comment by JoshuaLuckers** [comment]
The function `doEncode` is part of `Ext.util.JSON`.
