### ISSUE TITLE
Quick Create button issues

### ISSUE THREAD

**Issue by rainbowtiger** [modxcms/Collections#302]
1. The new Quick Create button should be off by default! I have 100 sites, and now after updating Collections I have to go through every single one, through every Collection on every site, and turn this off because I don't want it for my clients. I think new features should be opt-in, not opt-out.

2. There is a typo in the label for the Quick Create button in the Collection Settings screen: it says "Quick Crete Button" rather than "Quick Create Button".

**Comment by theboxer** [comment]
2. is duplicated of #298

1. sorry it's a default value for new views, but it's set through db, so it set it for all existing views when altering the table. too late to do anything with it
