### ISSUE TITLE
Can't set a Collection views column to use a TV name that has a period (.)

### ISSUE THREAD

**Issue by qodo** [modxcms/Collections#314]
I am trying to create a column for a TV called 
`publications.theme`

But I see an error when trying to set the column name to:
tv_publications.theme

![image](https://user-images.githubusercontent.com/3908836/90626995-70073d00-e213-11ea-88c0-44fa83415252.png)

Is there a reason this cannot allow . in the field as I use dot notation for most of my chunks and snippets.

Thanks

**Comment by theboxer** [comment]
Yes, there's a reason for that, you'll have to rename your TV.
