### ISSUE TITLE
Setting "Page size" does not work

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/Collections#316]
In my opinion, the "Page size" setting does not work, at least I changed this setting in the "Collection View - Blog", but there is no effect on collection grid.

I'm talking about:
![page_size](https://user-images.githubusercontent.com/12523676/98859160-cb437700-2472-11eb-9051-d382fe66bb5d.png)

Collection-3.7.1-pl
MODX-2.8.1

**Comment by theboxer** [comment]
It does work, but you need to clear `/cache/registry/state/` if you do any changes to the page size. As the page size is cached with `Ext.state.Manager`
