### ISSUE TITLE
Collections 4 beta: Default template is not created

### ISSUE THREAD

**Issue by Jako** [modxcms/Collections#338]
During a fresh install of Collections 4 beta the default Collections template is not installed and the Colllecton views grid is empty.

There is one error in the MODX logs and no error in the PHP log.
`[2022-01-13 16:28:11] (WARN @ /…/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php : 526) Could not load package metadata for package collections. Upgrade your model.`

**Comment by Jako** [comment]
I will check this again with the latest alpha.

**Comment by theboxer** [comment]
Feel free to reopen if the issue still exists

**Comment by Jako** [comment]
It is fixed, thanks!
