### ISSUE TITLE
Modx3 Collection - Collumns table missing and unable to save on Add View

### ISSUE THREAD

**Issue by temporalFluid** [modxcms/Collections#344]
From the collection Views page, when I click "Add View", I am delivered to index?template/create&namespace=collections  .  The page loads as expected except it is missing the "column" table at the bottom of the page.  All of the other panels show up and function.  I am unable to save the list without any errors.   The save icon appears rapidly dissapears and the view is not saved. 

I am able to duplicate views, edit them as usual with no errors, and save them with a "Successfully saved"
I receive no errors in the log.

Modx-3.0.0-rc2
PHP 8.1

Any advice on further troubleshooting?  

Thanks for your efforts!

**Comment by temporalFluid** [comment]
Greetings,

collections-4.0.0-beta1

I tried to do an upgrade through the /setup on top of the latest 2.8 version, however it failed, so I jumped back to the previous days working installation, and went to setup again.  This time I chose new installation.  So a new installation on top of an old one.  Not sure if that qualifies as fresh.  But it was the first time I got 3.0 working on my server.  The only other similar glitch is one that I was experiencing in 2.8... where I create a chunk, and if I try and save it with any content other then the title, nothing saves and I get a short "save animation"  without the green success box.  as though it starts to save and then just stops without concluding anything.  So I am unnable to create new chunks the traditional way and am left editing their content with phpmyadmin.   This only happens with chunks as far as I can see.  But it is very similar to what's happening with the collection view.  

So I tried creating a collection view this morning and the same thing happens.  I click add view, it brings me to the page with the template details and the "general, collection, and selection" tabs working as expected, however if I simply name it, and click save, nothing happens but a short green save swirl, no green success.

I can't think of how to troubleshoot this further if you have any suggestion I'd be willing to try.

**Comment by temporalFluid** [comment]
I tried the same configuration on a modxcloud and it seems to be functioning properly.  So I'm starting to assume it's the other server.  My fresh install maybe not fresh enough.  If I get time I will try and setup truely fresh on that server and see if the issue persists.

**Comment by theboxer** [comment]
👍  reopen this issue in case it'll persist
